version: "3"
services:
  nodejs-app:
    container_name: nodejs-app
    image: ranimmbarek/mon-app:v2
    ports:
      - "80:80"
    networks:
      - nodejs-app_network

  prometheus:
    container_name: prometheus-svc
    image: prom/prometheus
    ports:
      - "9091:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - nodejs-app_network

networks:
  nodejs-app_network:
    external: true
