apiVersion: apps/v1
kind: Deployment
metadata:`:;:
  name: mon-app
spec:
  replicas:  2
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
        - name: mon-app
          image: ranimmbarek/mon-app:v1
          ports:
            - containerPort: 80
