apiVersion: v1
kind: Service
metadata:
  name: mon-app-service
  labels:
    app: mon-app
spec:
  selector:
    app: mon-app
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80

